gitlab.page.size: 20
feign.hystrix.enabled: false

gitlab.url: https://gitlab.tech.lastmile.com
applicationId: ef875249c5c84b1e5a8b9fcdb01a5ff0ced097bc790ecf0573c0875dbe8d844a
secret: 54567221ebd2445361420569b8e42907570f35398510fb273542f556fbf1a334

security:
  oauth2:
    client:
      clientId: ${applicationId}
      clientSecret: ${secret}
      accessTokenUri: ${gitlab.url}/oauth/token
      userAuthorizationUri: ${gitlab.url}/oauth/authorize
    resource:
      userInfoUri: ${gitlab.url}/api/v3/user
