gitlab.page.size: 20
feign.hystrix.enabled: false

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${db.url:localhost:5432}/${db.name:postgres}
    username: ${db.username:postgres}
    password: ${db.password:postgres}

server.session.timeout: 864000	#ten days

security:
  oauth2:
    client:
      clientId: ${applicationId}
      clientSecret: ${secret}
      accessTokenUri: ${gitlab.url}/oauth/token
      userAuthorizationUri: ${gitlab.url}/oauth/authorize
    resource:
      userInfoUri: ${gitlab.url}/api/v3/user
